---
title: "GVPT 722 Final Exam"
author: "Ryan Bookstein"
format: 
  html:
    self-contained: true
editor: visual
execute: 
  message: false
  warning: false
---

Please read all of the questions and tables carefully. Be as brief as possible; extra calculations and incorrect information, even in the presence of correct information, will result in point deductions. If you need to make any assumptions, be sure to make them explicit. Show all formulas and all work.

## Question 1

Imagine you hypothesize that the probability of supporting a law to lower the voting age to 16 is lower for people age 65 and older than it is for people 30-64 years old. Using the table of survey results below answer questions 1a, 1b, and 1c. Please show all of your work.

| Age          | Oppose | Support | TOTAL |
|--------------|--------|---------|-------|
| 18-29        | 75     | 125     | 200   |
| 30-64        | 250    | 250     | 500   |
| 65 and older | 200    | 100     | 300   |
| TOTAL        | 525    | 475     | 1000  |

: Probability of Supporting a Law to Lower the Voting Age to 16 by Age (cell counts)

### Part A

What is the probability of supporting the law? (1 point)

475 / 1000 = 0.475

Based on the equation above, the probability of supporting the law is 47.5 percent.

### Part B

What is the probability of being 18-29 **or** supporting the law? Write the general (i.e. using symbols) formula you used to obtain your answer and show all of your work. (2 points)

P(A or B) = P(A) + P(B) - P(A and B)

0.2 + 0.475 - 0.125 = 0.55

Based on the equation above, the probability of being 18-29 or supporting the law is 55 percent.

### Part C

In terms of the substantive results (ignore statistical significance), does the evidence support your hypothesis? Explain, using details, how you know (no more than 2 sentences). (5 points)

Yes, the evidence supports my hypothesis that supporting a law to lower the voting age to 16 is lower for people age 65 and older than it is for people 30-64 years old. The probability of supporting the law for those aged 65 and older (1/3) is lower than the probability for those aged 30-64 (1/2).

## Question 2

Provide a political science example of an ordered categorical variable. (1 point)

A political science example of an ordered categorical variable is political ideology, which can be categorized as liberal, moderate, or conservative.

## Question 3

A recent study by Dr. Doofenshmirtz found that those who were randomly selected to be exposed to arguments that 16- and 17-year-olds are informed and engaged in local politics increased support for lowering the voting age to 16 by 10 percentage points, from a baseline of support of 45 percentage points in the control condition. On a quantitative methods exam Zuri, Jesse, and Teddy were asked if the effect was substantively significant. The question they were asked did not give any information about statistical significance. The answers they provided follow.

Jesse: The effect is substantively significant because 10 is a large number.

Teddy: We just don't know because there isn't any information about statistical significance.

Zuri: The effect is substantively significant because this information increases support over 50%, so a campaign stressing these points could help the policy pass by getting more than 50% support.

### Part A

True or False. Jesse would be marked incorrect. Just state True or False. (1 point)

True.

### Part B

True or False. Teddy would be marked as correct. Just state True or False. (1 point)

False.

### Part C

True or False. Zuri would be marked as correct. Just state True or False. (1 point)

True.

## Question 4

Use the information below and in Table 2 to answer questions 4a, 4b, 4c, and 4d.

**Dependent variable:**

-   United Nations Feeling Thermometer ranging from 0 (coldest) to 100 (warmest)

**Independent variables:**

-   Female, coded 1 for female and 0 for male;

-   Age, coded in years from 16-90.

The following results were obtained from a survey of 2,500 individuals age 16 to 90 in Africa, Asia, Europe, North America, Oceania, South America, and Africa.

| Independent variables | Coefficient | p-value |
|-----------------------|-------------|---------|
| Constant              | 51          | 0.000   |
| Female                | 2           | 0.000   |
| Age                   | 0.4         | 0.000   |

: Regression Results for Q4

### Part A

Using the information above, determine whether the following statement is **True or False, and fully explain why** in no more than 1 sentence: The interpretation of the coefficient on the constant term is useful on its own. (4 points)

False. The coefficient on the constant term is when all the independent variables are equal to zero, thus age cannot equal zero and zero is not meaningful.

### Part B

Using the information above, what is the substantive meaning of the coefficient on the Female variable? Answer in no more than 1 sentence and be sure to tailor the answer to the variables used in this example. (2 points)

The coefficient on the Female variable is 2, this means on average holding else constant females are associated with a 2 point increase on the feeling thermometer for the United Nations.

### Part C

True or False. Using the information above, because the coefficient on Female is larger than the coefficient on Age, the effect of being female on the United Nations Feeling thermometer is larger than the effect of age. Just state True or False. (1 point)

False.

### Part D

Using the information above, might the positive coefficient on Age be the result of older people being more knowledgeable about the United Nations? In no more than 1 sentence, explain your answer. (3 points)

Yes, because education level or awareness is not controlled for in the model the positive coefficient on Age may be the result of older people being more aware about the United Nations.

#### **Question 5**

### Part A

In an OLS model that includes X~2~, X~3~, and an interaction between X~2~ and X~3~, in one sentence explain how you would test the **overall** statistical significance of the relationship between X~2~ and the dependent variable. That is, what test would be used and what is the null hypothesis? (2 points)

I would test the overall statistical significance of the relationship between X2 and the dependent variables by using a F-Test. The null hypothesis would be that X2 and X3 are both equal to zero.

### Part B

Write out the equation for the effect of X~2~ on Y from the following OLS model:

**Y = β~1~ + β~2~X~2~ + β~3~X~3~ + β~23~X~2\*~X~3~ + β~4~X~4~ + u.** (3 points)

Equation for the effect of X2 on Y = β2 + β23X3

### Part C

Using the equation in 5b, if **X~2~** is a dummy variable coded as 0 or 1 and **X**~3~ is a categorical variable coded as 1, 2, or 3, is it useful to interpret **β~2~** on its own? **If it is not useful** to do so explain why it is not.  **If it is useful** to do so explain what it reveals.  Answer in [no more than 2 sentences]{.underline}. (3 points)

No, you cannot interpret B2 on its own because it shows the effect of X2 on Y when X3 equals zero, X3 cannot equal 0.

## Question 6

True or False. When using panel data, one of the key issues to address is the lack of independence across the observations. Just state True or False. (1 point)

True.

## Question 7

Answer the questions below based on the following information and the following table. (8 points total)

**Data**: 2020, individual level U.S. survey data

**Method**: Probit

**Dependent Variable**:

-   Voted or not, coded as `1` for voted and `0` for did not vote

**Independent Variables**:

-   Age (coded 18-92);

-   Education (coded in 5 categories (1 = No high school degree, 5 = Graduate Degree));

-   South (state is in the south and was part of the confederacy or not, 1=state is in the south, 0=state is not in the south).

| Independent variables | Coefficient   | Std. error | z-value | p-value |
|-----------------------|---------------|------------|---------|---------|
| Constant              | -3.79         | 0.04       | -94.75  | 0.000   |
| Age                   | 0.04          | 0.00       | 100.00  | 0.000   |
| Education             | 0.48          | 0.23       | 2.05    | 0.04    |
| South                 | -0.40         | 0.16       | 1.88    | 0.030   |
|                       |               |            |         |         |
| N                     | = 98,857      |            |         |         |
| Log likelihood        | = -56,089.376 |            |         |         |
| Chi sq                | = 13,196      |            |         |         |
| p-value               | = 0.000       |            |         |         |

: Probability of Voting Results for Q7

### Part A

Interpret the coefficient on the South variable (3 points)

The coefficient on the South variable is -0.40 and it statistically significant at the 0.05 level with a p-value of 0.030. Thus based on this information, we can determine that on average holding all else constant there is a statistically significant relationship associated with residing in a Southern state having a lower probability of voting compared to non southern states.

### Part B

In terms of the probability of voting, how you would determine the effect of living in a state that is in the south (which would allow you to then assess substantive significance)? That is, what is the effect of changing the South variable from 0 to 1? Set up all relevant equations **COMPLETELY** (but do not solve them), briefly explain what each does (no more than 1 sentence each), and explain how the effect of South is obtained (no more than 1 sentence). Note that this is **not** asking you to address substantive significance, just to set up the process. (5 points)

$$
(Y=1|X)=Φ(β0​+β1​×Age+β2​×Education+β3​×South)
$$\
This equation calculates the probability of voting (Y=1) given the values of the independent variables (Age, Education, South) using the CDF of the standard normal distribution Φ, where β0​, β1​, β2​, and β3​ are the coefficients of the intercept, Age, Education, and South variables.

$$
(Y=1|South=0)=Φ(β0​+β1​×Age+β2​×Education+β3​×(0))
$$

This equation calculates the probability of voting (Y=1) when the South variable is 0, given the values of the independent variables (Age, Education), using the CDF of the standard normal distribution Φ, where β0​, β1​, and β2​ are the coefficients of the intercept, Age, and Education variables.

$$
(Y=1| South=1)=Φ(β0​+β1​×Age+β2​×Education+β3​×(1))
$$\
This equation calculates the probability of voting (Y=1) when the South variable is 1, given the values of the independent variables (Age, Education), using the CDF of the standard normal distribution Φ, where β0​, β1​, β2​, and β3​ are the coefficients of the intercept, Age, Education, and South variables.

$$
ΔP=P(Y=1∣South=1)−P(Y=1∣South=0)
$$\
This equation calculates the change in the probability of voting when the South variable changes from 0 to 1 by subtracting the probability of voting when South is 0 from the probability of voting when South is 1.

## Bonus question

### Part A

True or False. If you run an OLS model and a test shows that the variance of the errors increases as one of the independent variables increases, i.e., there is heteroscedasticity, then the coefficients are unbiased but the standard errors are biased. Just state True or False. (1 point)

True.

### Part B

What is the OLS estimate of Y = α + ε? (That is, what does the OLS estimate of α equal?) (1 point)

The OLS estimate of Y = α + ε is the mean of Y, so the OLS estimate of α equals the mean of Y.

### Part C

Define consistency as it relates to a property of estimators. (2 points)

\
Consistency as it relates to a property of estimators refers to the property that as the sample size increases indefinitely, the estimator converges in probability to the true value of whats being estimated.
