---
title: "Problem set 1"
format: 
  html:
    self-contained: true
editor: visual
execute: 
  warning: false
  message: false
---

## Question 1

Imagine you hypothesize that the probability of voting for the incumbent in a two-candidate race is higher for those who are 30 to 65 years old than for those older than 65.

Using the table of survey results below answer questions 1a, 1b, 1c, and 1d. Please show all of your work.

| Age           | Challenger | Incumbent | TOTAL |
|---------------|------------|-----------|-------|
| 18 to 29      | 210        | 250       | 460   |
| 30 to 65      | 245        | 150       | 395   |
| Older than 65 | 160        | 150       | 310   |
| **TOTAL**     | 615        | 550       | 1165  |

: Voting for the Incumbent and Challenger by Age (cell counts)

### Part A

What is the probability of voting for the incumbent? (1 point)

550/1165

Based on the math above, the probability of voting for the incumbent is 0.472103 or 47.2103 percent.

### Part B

What is the probability of being 18-29 or voting for the incumbent? Write the general (i.e. using symbols) formula you used to obtain your answer and show all of your work. (2 points)

P(A / B) = P(A) + P(B) - P(A and B)

(460/1165) + (550/1165) - 250/1165

(0.3948498 + 0.472103) - 0.2145923

Based on the math above, the probability of being 18-29 or voting for the incumbent is 0.6523605 or 65.23 percent.

### Part C

In terms of the substantive results (ignore statistical significance), does the evidence support your hypothesis? Explain, using details, how you know (no more than 2 sentences). (5 points)

18-29: 250/460 = 0.5434783 30-65: 150/395 = 0.3797468 65 and older: 150/310 = 0.483871

Based on the table above, the data does not support my hypothesis. This is because the probability for voting for the incumbent is higher for those aged 65 and older (48.38 percent) compared to those aged 30 to 65 (37.97 percent).

### Part D

Imagine that the values in the **Total** column for each age group in *Table 1* remained the same, but the percentage voting for the incumbent in each age group was 51% (i.e. 51% of each age group voted for the incumbent). Now imagine that you were going to construct 90% confidence intervals, using the z table, for the percentage voting for the incumbent for each age group (don't actually do this). List the age groups in order starting with the one that would have the widest confidence interval to the one that would have the narrowest confidence interval, noting any ties. (3 points)

The order of the age groups starting with the widest confidence interval to narrowest confidence interval is older than 65 (310), 30 to 65 (395) 18 to 29 (460). This order is because the confidence intervals are wider when the sample size is smaller.

## Question 2

Provide a political science example of a nominal variable. (1 point)

A political science example of a nominal variable would be political party affiliation.

## Question 3

What is the OLS estimate of $Y = \beta_0 + \epsilon$? (That is, in terms of $Y$, what does the OLS estimate of $\beta_0$ equal?) (2 points)

The OLS estimate of $Y = \beta_0 + \epsilon$, in terms of $Y$ is $\beta_0$ is the intercept and the sample mean of the DV $Y$.

## Question 4

Answer the questions below based on the following information and table.

$N = 1,200$ from a random sample of 18 and older Canadians.

**Dependent variable:** Feeling Thermometer Rating of George W. Bush (0 to 100: 0 = very cold, 100 = very warm)

**Independent variables:** age (in years), education (in years), have access to U.S. TV stations (1 = yes, 0 = no), ideology (7 point scale: 1 = very liberal, 7 = very conservative)

| Independent variables | Coefficient | SE  | p-value |
|-----------------------|-------------|-----|---------|
| Constant              | 50          | 20  | 0.0126  |
| Age                   | 0.5         | 1   | 0.6172  |
| Education             | -2          | 0.2 | 0.0000  |
| U.S. TV Access        | -5          | 2   | 0.0126  |
| Ideology              | 6           | 3.2 | 0.0610  |

: Hypothetical Regression Results Predicting George W. Bush Thermometer Ratings

### Part A

Calculate the t-statistic for `Education`. (1 point)

-2 / 0.2

Based on the math above, the t-statistic for `Education` is -10.

### Part B

Interpret the results for the `Education` variable, i.e. BRIEFLY discuss the substantive meaning of the results (1 sentence), substantive significance (no more than 2 sentences), and statistical significance (1 sentence). (5 points)

The substantive meaning of the results show a negative coefficient for the `Education` variable, we can conclude that with each year of education there is a decrease in 2 points in the feeling thermometer for George W. Bush. The substantive significance suggests individuals with higher levels of education have lower feelings towards George W. Bush, showing a relationship between education and attitudes towards George W. Bush. Finally, the statistical significance of the relationship is seen with the p-value of 0. This means we can conclude there is a strong relationship between years of education and feelings towards George W. Bush.

### Part C

In this context, is the coefficient on the constant term useful on its own? Why or why not (1 sentence) (5 points)

Yes, in this context, the coefficient on the constant term can be useful on its own. This is because it provides an estimated value for the dependent variable when all independent variables are equal to zero.

### Part D

Is the coefficient on `U.S. TV access` statistically significant at the 5% error level? (1 point)

Yes, `U.S. TV access` is statistically significant at the 5% error level because its p-value is less than 0.05.

### Part E

Is the coefficient on `U.S. TV access` statistically significant at the 1% error level? (1 point)

No, `U.S. TV access` is not statistically significant at the 1% error level because its p-value is greater than 0.01.

### Part F

Based on the results in *Table 2*, might the negative coefficient on `U.S. TV Access` be the result of more educated people being more likely to have access to U.S. TV? In no more than 1 sentence, explain your answer. (3 points)

Yes, based on the results in Table 2 the negative coefficient on `U.S TV Access` could be the result of more educated people being more likely to have access to U.S. TV. The two variables could be confounding, implying that educated individuals may be likely to have less access to TV, thus confounding the results of US TV Access.
